# Generated by Django 3.2.7 on 2021-09-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('symbol', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
    ]
