# Generated by Django 3.2.7 on 2021-09-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbol',
            options={'verbose_name': 'Symbol', 'verbose_name_plural': 'Symbols'},
        ),
        migrations.AlterModelTable(
            name='symbol',
            table='symbol',
        ),
    ]
