# Generated by Django 3.2.7 on 2021-09-06 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptocurrency', '0002_auto_20210905_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cryptocurrency.symbol')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watch List',
                'verbose_name_plural': 'Watch List',
                'db_table': 'watch_list',
            },
        ),
    ]
