# Generated by Django 3.2.7 on 2021-09-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0003_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ('symbol',), 'verbose_name': 'Symbol', 'verbose_name_plural': 'Symbols'},
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='symbol',
            field=models.OneToOneField(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cryptocurrency.symbol'),
        ),
    ]
