# Generated by Django 3.2.7 on 2021-09-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0004_auto_20210906_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_unix_time', models.IntegerField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.FloatField()),
                ('volume', models.FloatField()),
                ('start_datetime', models.DateTimeField()),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='cryptocurrency.watchlist')),
            ],
            options={
                'verbose_name': 'OHLC',
                'verbose_name_plural': 'OHLCs',
                'db_table': 'ohlc',
                'ordering': ('symbol', '-start_datetime'),
            },
        ),
    ]
