# Generated by Django 3.2.7 on 2021-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0005_ohlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohlc',
            name='interval',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ohlc',
            unique_together={('start_datetime', 'symbol')},
        ),
    ]
