# Generated by Django 3.2.7 on 2021-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0006_auto_20210906_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlc',
            name='interval',
            field=models.CharField(max_length=16),
        ),
    ]
