# Generated by Django 3.2.7 on 2021-09-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0007_alter_ohlc_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleStick',
            fields=[
                ('ohlc', models.OneToOneField(db_column='ohlc_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cryptocurrency.ohlc')),
                ('length', models.FloatField()),
            ],
            options={
                'verbose_name': 'CandleStick',
                'verbose_name_plural': 'CandleSticks',
                'db_table': 'candlestick',
            },
        ),
    ]
