# Generated by Django 3.2.7 on 2021-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0009_auto_20210908_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlestick',
            name='max_o1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='candlestick',
            name='max_o2',
            field=models.BooleanField(null=True),
        ),
    ]
