# Generated by Django 3.2.7 on 2021-09-11 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptocurrency', '0010_auto_20210908_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCurrency',
            fields=[
                ('fee_currency', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Fee Currency',
                'verbose_name_plural': 'Fee Currencies',
                'db_table': 'fee_currency',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('op_type', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=16)),
                ('side', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('size', models.FloatField()),
                ('funds', models.FloatField()),
                ('deal_funds', models.FloatField()),
                ('deal_size', models.FloatField()),
                ('stp', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('time_in_force', models.CharField(blank=True, max_length=3, null=True)),
                ('cancel_after', models.IntegerField(blank=True, null=True)),
                ('stop', models.CharField(blank=True, choices=[('loss', 'loss'), ('entry', 'entry')], max_length=16, null=True)),
                ('stop_price', models.FloatField(blank=True, null=True)),
                ('stop_triggered', models.BooleanField(blank=True, null=True)),
                ('post_only', models.BooleanField(blank=True, default=False, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('iceberg', models.BooleanField(blank=True, default=False, null=True)),
                ('visible_size', models.FloatField(blank=True, default=0, null=True)),
                ('channel', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('client_oid', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('remark', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('fee', models.FloatField()),
                ('is_active', models.BooleanField()),
                ('cancel_exists', models.BooleanField()),
                ('created_at', models.IntegerField()),
                ('trade_type', models.CharField(choices=[('TRADE', 'Spot Trading'), ('MARGIN_TRADE', 'Margin Trading')], max_length=16)),
                ('fee_currency', models.ForeignKey(db_column='fee_currency', on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.feecurrency')),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.PROTECT, to='cryptocurrency.symbol')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ('created_at',),
            },
        ),
    ]
