# Generated by Django 3.2.7 on 2021-09-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0011_feecurrency_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cancel_exists',
            new_name='cancel_exist',
        ),
    ]
