# Generated by Django 3.2.7 on 2021-09-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0013_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=10)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('strategy', models.CharField(blank=True, max_length=32, null=True)),
                ('position_type', models.CharField(blank=True, max_length=16, null=True)),
                ('position_time', models.IntegerField()),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='cryptocurrency.watchlist')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'position',
                'ordering': ('order_id',),
            },
        ),
    ]
